version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "image-scraper"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1sncbhh6kkruw"
s3_prefix = "image-scraper"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=190047048560.dkr.ecr.ap-northeast-2.amazonaws.com/imagescraper95ffd0b0/helloworldfunction19d43fc4repo"]
